### ISSUE TITLE
Finishing touches checklist

### ISSUE THREAD

**Issue by bradleyboehmke** [rstudio-conf-2020/dl-keras-tf#6]
- [x] modify data paths in notebooks since server setup directories differ slightly
- [x] revise notebooks so minimal slides are required
- [x] add policy slide to intro
- [x] add server instructions to README/slides
- [x] add survey link to wrap-up slides
- [x] add color sticky question indicator to intro slide???
